<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Teacher;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                'nip' => '198501012010011001',
                'name' => 'Budi Santoso, S.Pd',
                'email' => 'budi@smp.sch.id',
                'phone' => '081234567801',
                'address' => 'Jl. Pendidikan No. 1, Medan',
                'gender' => 'L',
                'birth_date' => '1985-01-01',
                'status' => 'active',
            ],
            [
                'nip' => '198602152011012001',
                'name' => 'Siti Aminah, S.Pd',
                'email' => 'siti@smp.sch.id',
                'phone' => '081234567802',
                'address' => 'Jl. Guru No. 2, Medan',
                'gender' => 'P',
                'birth_date' => '1986-02-15',
                'status' => 'active',
            ],
            [
                'nip' => '198703202012011002',
                'name' => 'Ahmad Yani, S.Pd',
                'email' => 'ahmad@smp.sch.id',
                'phone' => '081234567803',
                'address' => 'Jl. Ilmu No. 3, Medan',
                'gender' => 'L',
                'birth_date' => '1987-03-20',
                'status' => 'active',
            ],
            [
                'nip' => '198804102013012001',
                'name' => 'Dewi Lestari, S.Pd',
                'email' => 'dewi@smp.sch.id',
                'phone' => '081234567804',
                'address' => 'Jl. Sosial No. 4, Medan',
                'gender' => 'P',
                'birth_date' => '1988-04-10',
                'status' => 'active',
            ],
            [
                'nip' => '198905252014011001',
                'name' => 'John Anderson, S.Pd',
                'email' => 'john@smp.sch.id',
                'phone' => '081234567805',
                'address' => 'Jl. Bahasa No. 5, Medan',
                'gender' => 'L',
                'birth_date' => '1989-05-25',
                'status' => 'active',
            ],
            [
                'nip' => '199006122015012001',
                'name' => 'Rina Wati, S.Ag',
                'email' => 'rina@smp.sch.id',
                'phone' => '081234567806',
                'address' => 'Jl. Agama No. 6, Medan',
                'gender' => 'P',
                'birth_date' => '1990-06-12',
                'status' => 'active',
            ],
            [
                'nip' => '199107182016011001',
                'name' => 'Joko Susilo, S.Pd',
                'email' => 'joko@smp.sch.id',
                'phone' => '081234567807',
                'address' => 'Jl. Olahraga No. 7, Medan',
                'gender' => 'L',
                'birth_date' => '1991-07-18',
                'status' => 'active',
            ],
            [
                'nip' => '199208302017012001',
                'name' => 'Hasan Basri, S.Ag',
                'email' => 'hasan@smp.sch.id',
                'phone' => '081234567808',
                'address' => 'Jl. Pendidikan No. 8, Medan',
                'gender' => 'L',
                'birth_date' => '1992-08-30',
                'status' => 'active',
            ],
            // Data tambahan untuk melengkapi 20 guru
            [
                'nip' => '199309052018012002',
                'name' => 'Linda Sari, S.Pd',
                'email' => 'linda@smp.sch.id',
                'phone' => '081234567809',
                'address' => 'Jl. Matematika No. 9, Medan',
                'gender' => 'P',
                'birth_date' => '1993-09-05',
                'status' => 'active',
            ],
            [
                'nip' => '199410202019011003',
                'name' => 'Robert Wijaya, S.Pd',
                'email' => 'robert@smp.sch.id',
                'phone' => '081234567810',
                'address' => 'Jl. Sains No. 10, Medan',
                'gender' => 'L',
                'birth_date' => '1994-10-20',
                'status' => 'active',
            ],
            [
                'nip' => '199511152020012003',
                'name' => 'Maya Indah, S.Pd',
                'email' => 'maya@smp.sch.id',
                'phone' => '081234567811',
                'address' => 'Jl. Sejarah No. 11, Medan',
                'gender' => 'P',
                'birth_date' => '1995-11-15',
                'status' => 'active',
            ],
            [
                'nip' => '199612252021011004',
                'name' => 'David Pranata, S.Kom',
                'email' => 'david@smp.sch.id',
                'phone' => '081234567812',
                'address' => 'Jl. Teknologi No. 12, Medan',
                'gender' => 'L',
                'birth_date' => '1996-12-25',
                'status' => 'active',
            ],
            [
                'nip' => '197802142005011001',
                'name' => 'Sri Rahayu, M.Pd',
                'email' => 'sri@smp.sch.id',
                'phone' => '081234567813',
                'address' => 'Jl. Kepala Sekolah No. 13, Medan',
                'gender' => 'P',
                'birth_date' => '1978-02-14',
                'status' => 'active',
            ],
            [
                'nip' => '198003052006012002',
                'name' => 'Hendra Gunawan, S.Pd, M.Pd',
                'email' => 'hendra@smp.sch.id',
                'phone' => '081234567814',
                'address' => 'Jl. Wakasek No. 14, Medan',
                'gender' => 'L',
                'birth_date' => '1980-03-05',
                'status' => 'active',
            ],
            [
                'nip' => '198204152007011003',
                'name' => 'Anita Desiana, S.Pd',
                'email' => 'anita@smp.sch.id',
                'phone' => '081234567815',
                'address' => 'Jl. Seni No. 15, Medan',
                'gender' => 'P',
                'birth_date' => '1982-04-15',
                'status' => 'active',
            ],
            [
                'nip' => '198305302008012004',
                'name' => 'Fajar Nugroho, S.Pd',
                'email' => 'fajar@smp.sch.id',
                'phone' => '081234567816',
                'address' => 'Jl. Prakarya No. 16, Medan',
                'gender' => 'L',
                'birth_date' => '1983-05-30',
                'status' => 'active',
            ],
            [
                'nip' => '199707082022011005',
                'name' => 'Kevin Siregar, S.Pd',
                'email' => 'kevin@smp.sch.id',
                'phone' => '081234567817',
                'address' => 'Jl. Muda No. 17, Medan',
                'gender' => 'L',
                'birth_date' => '1997-07-08',
                'status' => 'active',
            ],
            [
                'nip' => '199808192023012005',
                'name' => 'Nina Fitriani, S.Pd',
                'email' => 'nina@smp.sch.id',
                'phone' => '081234567818',
                'address' => 'Jl. Baru No. 18, Medan',
                'gender' => 'P',
                'birth_date' => '1998-08-19',
                'status' => 'active',
            ],
            [
                'nip' => '197512032000011001',
                'name' => 'Bambang Supriyadi, M.Pd',
                'email' => 'bambang@smp.sch.id',
                'phone' => '081234567819',
                'address' => 'Jl. Veteran No. 19, Medan',
                'gender' => 'L',
                'birth_date' => '1975-12-03',
                'status' => 'active',
            ],
            [
                'nip' => '199909252024011006',
                'name' => 'Rizky Pratama, S.Pd',
                'email' => 'rizky@smp.sch.id',
                'phone' => '081234567820',
                'address' => 'Jl. Teratai No. 20, Medan',
                'gender' => 'L',
                'birth_date' => '1999-09-25',
                'status' => 'active',
            ],
        ];

        foreach ($teachers as $teacher) {
            Teacher::create($teacher);
        }
    }
}